# tabs and spacing matter in this file.
version: "3"
# A service is a container
services:
  api:
    build: .
  # The outside world need to be able to speak to our container, so we need to open up a port
    ports:
      #- <port on localhost(any open port)>:<port on container(same as in Dockerfile)>
      - 8000:8000


# docker-compose up -d
# docker ps -a # ...see if it crashed
# docker logs fastapi-api-1
