"""autogenerate all things remaining

Revision ID: b0d6ff8dc0ed
Revises: 2ff83aa76ae1
Create Date: 2022-02-10 17:37:35.991689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d6ff8dc0ed'
down_revision = '2ff83aa76ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
