"""re-trying to autogenerate all

Revision ID: ff8d4bd3ed58
Revises: b0d6ff8dc0ed
Create Date: 2022-02-12 15:03:56.268927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8d4bd3ed58'
down_revision = 'b0d6ff8dc0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
